post/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    
    path('add_to_statistics/',
        views.AddToStatisticsAPIView.as_view(),
        name='add_to_statistics'),
]

quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('post.urls')),
]

post/models.py
from django.db import models
from django.utils.text import slugify


class Language(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(max_length=40)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.CharField(max_length=50)
    
    text = models.TextField()
    text_language = models.ForeignKey(Language, related_name='language_text',
        on_delete=models.DO_NOTHING)

    translation = models.TextField()
    translation_language = models.ForeignKey(Language,
        related_name='language_translation',
        on_delete=models.DO_NOTHING)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.translation:
            return self.translation[:50]
        return self.text[:50]


class Statistic(models.Model):
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING, related_name='statistics')
    used_times = models.PositiveIntegerField(default=0)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post)

post/views.py
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator

from rest_framework.views import APIView
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt

from .models import Post, Statistic


class HomeView(TemplateView):
    template_name = 'post/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.objects.order_by("?").first()
        context['post'] = post

        last_seen_posts = Statistic.objects.order_by('updated_at')[:5]
        context['last_seen_posts'] = last_seen_posts
        return context


class AddToStatisticsAPIView(APIView):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, format=None):
        post_id = request.data.get('post_id')
        obj, created = Statistic.objects.get_or_create(post_id=post_id)
        obj.used_times += 1
        obj.save()
        
        if created:
            return Response({
                'message': 'Post added to statistics'
            })
        else:
            return Response({
                'message': "Post's statistics updated"
            })

post/templates/post/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Photo Amin</title>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

  <style>
    .section {
      padding-top: 4vw;
      padding-bottom: 4vw;
    }

    .tabs .indicator {
      background-color: #1a237e;
    }

    .tabs .tab a:focus, .tabs .tab a:focus.active {
      background: transparent;
    }

    @media screen and (max-width: 670px) {
      header {
        min-height: 500px;
      }
    }
  </style>
</head>
<body>
  <header>
    <nav class="container">
      <div class="nav-wrapper">
        <a href="#" class="brand-logo" style="margin-left: 30px;">Quotes</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        </ul>
      </div>
    </nav>
  </header>

  <div class="container" style="background-color: #ffebdf !important; margin-top: 16px; padding: 10px;">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col m12">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Quote <span class="badge blue new" data-badge-caption="">
              {% if post.statistics.used_times %}
                {{ post.statistics.used_times }}
              {% else %}
                0
              {% endif %}
            </span></span>
            <p>{{ post.text }}</p>
            <hr>
            <p>{{ post.translation }}</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col s12 m6">
        <button class="btn btn-large" style="width: 100%; margin-top: 6px;">Get new quote</button>
      </div>
      <div class="col s12 m6">
        <button id="use_this_quote" class="btn btn-large" style="width: 100%; margin-top: 6px;">Use this quote</button>
      </div>
    </div>
  </div>

  <div class="container" style="background-color: #f0eecc !important; margin-top: 10px; padding: 10px;">
    <div class="row">
      <div class="col m12">
        <h3 class="center">Last seen quotes</h3>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Quote 1</span>
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Quote 2</span>
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="card blue-grey darken-3">
          <div class="card-content white-text">
            <span class="card-title">Quote 3</span>
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Quote 4</span>
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col m12">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Quote 5</span>
            <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="page-footer grey darken-3">
    <div class="footer-copyright grey darken-4">
      <div class="container center-align">&copy; 2021 Designed by Amin</div>
    </div>
  </footer>

  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script>
    $('#use_this_quote').click(function() {
      var post_id = {{ post.id }}
      $.ajax({
        type: 'POST',
        url: "{% url 'post:add_to_statistics' %}",
        data: {
          'post_id': post_id
        },
        success: function(data) {
          console.log('success')
        },
        error: function(err) {
          console.log('error')
        }
      })
    })
  </script>
</body>
</html>